name: Common Linting

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - "accounts/**"

permissions:
  contents: read

jobs:
  lint:
    name: Super-Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-linter
        uses: super-linter/super-linter@61abc07d755095a68f4987d1c2c3d1d64408f1f9 # 8.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          TERRAFORM_TFLINT_CONFIG_FILE: .tflint.custom.hcl
          VALIDATE_JSCPD: false
          VALIDATE_CHECKOV: false
          VALIDATE_TERRAFORM_TERRASCAN: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_MARKDOWN_PRETTIER: false
          FIX_YAML_PRETTIER: true
          VALIDATE_BIOME_LINT: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_TRIVY: false
          FIX_TERRAFORM_FMT: true
          FILTER_REGEX_EXCLUDE: .*(github/linters|specify/).*
          VALIDATE_SPELL_CODESPELL: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_RUFF_FORMAT: false

